apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  AUTH_SECRET: Ym1Eb2RFWnVTRGtuRWdiSmM2SG8xVklKQWN0MUFmTklEeEtrTEZJMDVDRT0=
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9wYXJ0aHAwMjI3MTI6V0VSUTZQQ0tHMHM4c3A2YkByb2xlYmFzZS1hcHAuZ2g0amcubW9uZ29kYi5uZXQvcm9sZWJhc2UtYXBwP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPXJvbGViYXNlLWFwcA==
