name: Build and Deploy to Kubernetes (Minikube)

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # this should be 'self-hosted' if on your VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t parth2k2/rollbase-app-web:latest .

      - name: Push image
        run: docker push parth2k2/rollbase-app-web:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted  # must run on your Ubuntu VM where Minikube is set up

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load image into Minikube
        run: |
          minikube image load parth2k2/rollbase-app-web:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/configmap.yml
          kubectl apply -f k8s/secret.yml
          kubectl apply -f k8s/mongodb-deployment.yml
          kubectl apply -f k8s/mongodb-service.yml
          kubectl apply -f k8s/app-deployment.yml
          kubectl apply -f k8s/app-service.yml

